### ISSUE TITLE
deploy to Heroku failing

### ISSUE THREAD

**Issue by Stirling** [diowa/icare#40]
Thank you for a great looking product, especially appreciate the tight Facebook integration.

However a couple attempts to deploy to Heroku with no luck. Here's what I get:

```
-----> Deleting 5 files matching .slugignore patterns.
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.0
-----> Installing dependencies using bundler 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Fetching git://github.com/DavyJonesLocker/client_side_validations.git
       Fetching git://github.com/DavyJonesLocker/client_side_validations-simple_form.git
       Using json 1.8.3
       Installing minitest 5.8.3
       Installing rake 10.4.2
       Installing i18n 0.7.0
       Installing thread_safe 0.3.5
       Installing builder 3.2.2
       Installing erubis 2.7.0
       Installing mini_portile2 2.0.0
       Installing rack 1.6.4
       Installing mime-types 2.99
       Installing arel 6.0.3
       Installing addressable 2.4.0
       Installing airbrake-ruby 1.0.1
       Installing execjs 2.6.0
       Installing thor 0.19.1
       Installing regexp_parser 0.3.1
       Using bundler 1.9.7
       Installing concurrent-ruby 1.0.0
       Installing bcrypt 3.1.10
       Installing bson 4.0.0
       Installing daemons 1.2.3
       Installing coffee-script-source 1.10.0
       Installing multipart-post 2.0.0
       Installing orm_adapter 0.5.0
       Installing google-analytics-rails 0.0.6
       Installing multi_json 1.11.2
       Installing tilt 1.4.1
       Installing hashie 3.4.3
       Installing http_accept_language 2.0.5
       Installing timeliness 0.3.7
       Installing jwt 1.5.2
       Installing origin 2.1.1
       Installing stringex 2.5.2
       Installing mono_logger 1.1.0
       Installing moped 1.5.3
       Installing multi_xml 0.5.5
       Installing newrelic_rpm 3.14.1.311
       Installing rails_serve_static_assets 0.0.4
       Installing rails_stdout_logging 0.0.4
       Installing kgio 2.10.0
       Installing redis 3.2.2
       Installing raindrops 0.15.0
       Installing sass 3.4.20
       Installing eventmachine 1.0.8
       Installing simpleconfig 2.0.1
       Installing rgeo 0.5.2
       Installing user_agent_parser 2.3.0
       Installing temple 0.7.6
       Installing i18n-js 2.1.2
       Installing tzinfo 1.2.2
       Installing warden 1.2.4
       Installing rack-test 0.6.3
       Installing rack-protection 1.5.3
       Installing vegas 0.1.11
       Installing mail 2.6.3
       Installing airbrake 5.0.1
       Installing autoprefixer-rails 6.2.2
       Installing uglifier 2.7.2
       Installing js_regex 1.0.11
       Installing sprockets 3.5.2
       Installing coffee-script 2.4.1
       Installing mongo 2.2.1
       Installing faraday 0.9.2
       Installing omniauth 1.3.1
       Installing newrelic_moped 1.0.1
       Installing jc-validates_timeliness 3.1.1
       Installing redis-namespace 1.5.2
       Installing rails_12factor 0.0.3
       Installing nokogiri 1.6.7.1
       Installing secure_headers 2.4.4
       Installing thin 1.6.4
       Installing slim 3.0.6
       Installing activesupport 4.2.5
       Installing sinatra 1.4.6
       Installing handlebars_assets 0.22.0
       Installing koala 2.2.0
       Installing oauth2 1.0.0
       Installing loofah 2.0.3
       Installing rails-deprecated_sanitizer 1.0.3
       Installing slim_assets 0.0.2
       Installing globalid 0.3.6
       Installing activemodel 4.2.5
       Installing rabl 0.11.7
       Installing resque 1.25.2
       Installing unicorn 5.0.1
       Installing omniauth-oauth2 1.4.0
       Installing rails-html-sanitizer 1.0.2
       Installing rails-dom-testing 1.0.7
       Installing activejob 4.2.5
       Installing activerecord 4.2.5
       Installing omniauth-facebook 3.0.0
       Installing mongoid 5.0.2
       Installing mongoid_geospatial 3.1.0
       Installing actionview 4.2.5
       Installing mongoid-compatibility 0.3.1
       Installing mongoid-slug 5.1.1
       Installing mongoid_paranoia 0.2.1
       Installing actionpack 4.2.5
       Installing actionmailer 4.2.5
       Installing sprockets-rails 2.3.3
       Installing railties 4.2.5
       Installing simple_form 3.2.1
       Installing kaminari 0.16.3
       Installing jquery-rails 4.0.5
       Installing coffee-rails 4.1.1
       Installing rails 4.2.5
       Installing responders 2.1.1
       Installing turbolinks 2.5.3
       Using client_side_validations 4.2.0 from git://github.com/DavyJonesLocker/client_side_validations.git (at master)
       Installing sass-rails 5.0.4
       Installing slim-rails 3.0.1
       Using client_side_validations-simple_form 3.2.0 from git://github.com/DavyJonesLocker/client_side_validations-simple_form.git (at master)
       Installing jquery-turbolinks 2.1.0
       Installing devise 3.5.3
       Installing twbs_sass_rails 4.0.0
       Bundle complete! 65 Gemfile dependencies, 115 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from handlebars_assets:
       Remember to rake assets:clean or rake assets:purge on update! this is required because of handlebars updates
       Bundle completed (47.69s)
       Cleaning up the bundler cache.
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       Airbrake::Error: the 'default' notifier isn't configured
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:282:in `call_notifier'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:236:in `build_notice'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       Airbrake::Error: the 'default' notifier isn't configured
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:282:in `call_notifier'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:236:in `build_notice'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       Airbrake::Error: both :project_id and :project_key are required
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby/notifier.rb:30:in `initialize'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:104:in `new'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:104:in `configure'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/config/initializers/airbrake.rb:1:in `<top (required)>'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/config/environment.rb:8:in `<top (required)>'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       Tasks: TOP => assets:precompile => assets:environment
       (See full trace by running task with --trace)
       /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:282:in `call_notifier': the 'default' notifier isn't configured (Airbrake::Error)
       from /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:149:in `notify_sync'
       from /tmp/build_f262abb684b86781cacfa06524a67b9a/diowa-icare-bf17ae0/vendor/bundle/ruby/2.3.0/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:291:in `block in <top (required)>'
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app
```

**Comment by tagliala** [comment]
Fixed, thanks!

**Comment by Stirling** [comment]
Thank you for the quick fix!

**Comment by pepcha** [comment]
Hi, 

I am currently encountering the same issue. Could you please help me out. 

Thanks
Lavanya

**Comment by tagliala** [comment]
@pepcha Sorry, I'm locked on https://github.com/heroku/rails_stdout_logging/pull/22

**Comment by pepcha** [comment]
Thanks @tagliala It worked.. Now I need to figure out how to set this up and change things.. I am a totally newbie in Ruby.. This is my first app :)

**Comment by tagliala** [comment]
@pepcha please follow #44
