### ISSUE TITLE
Cannot run in production environment

### ISSUE THREAD

**Issue by tagliala** [diowa/icare#44]
Seems related to Rails 4.2.6 + mongoid

```
$ RAILS_ENV=production rake routes
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:250:in `set_log_levels'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:132:in `load_configuration'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/config.rb:88:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid.rb:99:in `load!'
~/.rvm/gems/ruby-2.3.0/gems/mongoid-5.1.1/lib/mongoid/railtie.rb:59:in `block in <class:Railtie>'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
~/dev/icare/config/environment.rb:9:in `<top (required)>'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
~/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => routes => environment
(See full trace by running task with --trace)

```

**Comment by tagliala** [comment]
https://github.com/heroku/rails_stdout_logging/issues/23

**Comment by Aethelflaed** [comment]
:+1: same issue here, I will downgrade in the meantime.
